In [2]:
#pip install newsapi-python pandas nltk

Requirement already satisfied: newsapi-python in c:\users\athen\anaconda3\envs\appliedml\lib\site-packages (0.2.7)
Requirement already satisfied: pandas in c:\users\athen\anaconda3\envs\appliedml\lib\site-packages (2.3.2)
Requirement already satisfied: nltk in c:\users\athen\anaconda3\envs\appliedml\lib\site-packages (3.9.1)
Requirement already satisfied: requests<3.0.0 in c:\users\athen\anaconda3\envs\appliedml\lib\site-packages (from newsapi-python) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\athen\anaconda3\envs\appliedml\lib\site-packages (from requests<3.0.0->newsapi-python) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\athen\anaconda3\envs\appliedml\lib\site-packages (from requests<3.0.0->newsapi-python) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\athen\anaconda3\envs\appliedml\lib\site-packages (from requests<3.0.0->newsapi-python) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\athen\anaconda3\envs\appliedml\lib\site-packages (from requests<3.0.0->newsapi-python) (2025.8.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\athen\anaconda3\envs\appliedml\lib\site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\athen\anaconda3\envs\appliedml\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\athen\anaconda3\envs\appliedml\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\athen\anaconda3\envs\appliedml\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: click in c:\users\athen\anaconda3\envs\appliedml\lib\site-packages (from nltk) (8.3.0)
Requirement already satisfied: joblib in c:\users\athen\anaconda3\envs\appliedml\lib\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\athen\anaconda3\envs\appliedml\lib\site-packages (from nltk) (2025.9.18)
Requirement already satisfied: tqdm in c:\users\athen\anaconda3\envs\appliedml\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: six>=1.5 in c:\users\athen\anaconda3\envs\appliedml\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: colorama in c:\users\athen\anaconda3\envs\appliedml\lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [2]:
#microsoft alphabet meta
from newsapi import NewsApiClient
import pandas as pd

newsapi = NewsApiClient(api_key="e50e3a3dd988450c830e80887853a65c")

articles = newsapi.get_everything(
    q="Microsoft OR Meta OR Alphabet",
    language='en',
    sort_by="publishedAt",
    from_param="2025-11-01",
    page_size=100
)

data = []
for a in articles["articles"]:
    data.append({
        "title": a["title"],
        "description": a["description"],
        "content": a["content"],
        "publishedAt": a["publishedAt"],
        "source": a["source"]["name"]
    })

df = pd.DataFrame(data)
print(df.head())

                                               title  \
0  Searching for new architecture & design jobs? ...
1  Alphabet AI chips, Gemini model position it to...
2  Chrome Finally Gets Vertical Tabs After Years ...
3  Existential OCD: When 'Why Am I Here?' Won’t L...
4  AMD Stock Tanks Amid Shifting Sands In Semicon...

                                         description  \
0  In this week's curated employer highlight from...
1  Shares in the Mountain View, California-based ...
2  Google Chrome is finally catching up to what e...
3  What if your endless questions about life, dea...
4  Advanced Micro Devices, Inc. (NASDAQ:AMD) shar...

                                             content           publishedAt  \
0  In this week's curated employer highlight from...  2025-11-25T15:38:00Z
1  A rally in Alphabet shares is poised to shake ...  2025-11-25T15:36:25Z
2  Google Chrome is finally catching up to what e...  2025-11-25T15:32:34Z
3  Picture this: Life looks fine from the outside...  2025-11-25T15:32:05Z
4  Advanced Micro Devices, Inc. (NASDAQ:AMD) shar...  2025-11-25T15:31:51Z

               source
0           Archinect
1  The Times of India
2     Gadgethacks.com
3    Psychology Today
4          Biztoc.com

In [3]:
def detect_company(text):
    t = str(text).lower()
    if "microsoft" in t:
        return "Microsoft"
    elif "meta" in t:
        return "Meta"
    elif "alphabet" in t or "google" in t:
        return "Alphabet"
    else:
        return "Unknown"

df["company"] = df["content"].apply(detect_company)

In [5]:
#intergrate others' data (including other companies
import pandas as pd

df2 = pd.read_csv("web_scraping_data.csv")

df2.head()

,title,company_name,description,content,publishedAt,source
0,Analysts upgrade AAPL following Apple Inc. res...,Apple Inc.,Analysts upgrade AAPL following Apple Inc. res...,Apple Inc. responds to activist investor Ellio...,4/2/2025,Barron's
1,Apple Inc. (AAPL) shares gain 4.7% on analyst ...,Apple Inc.,Apple Inc. (AAPL) shares gain 4.7% on analyst ...,Valuation multiples for AAPL include P/E of 28...,9/27/2024,CNBC
2,Apple Inc. Vision Pro succeeds in market [1716...,Apple Inc.,Apple Inc. Vision Pro succeeds in market [1716...,Apple Inc. demonstrated scaling capabilities w...,5/21/2024,WSJ
3,AAPL rises as Apple Inc. reports financial dat...,Apple Inc.,AAPL rises as Apple Inc. reports financial dat...,Sum-of-parts valuation for Apple Inc. assigns ...,7/14/2025,MarketWatch
4,Apple Inc. (AAPL) shares unchanged 2.4% on ana...,Apple Inc.,Apple Inc. (AAPL) shares unchanged 2.4% on ana...,Apple Inc. participates in 6 secular themes in...,2/22/2024,CNBC

In [9]:
# data preprocessing
# Because we already clean data manually, we will simply do duplicates check now
df[df.duplicated(subset=["content"])]
df=df.drop_duplicates(subset=["content"])
df[df.duplicated(subset=["content"])]

Empty DataFrame
Columns: [title, description, content, publishedAt, source, company]
Index: []

In [5]:
#pip install nltk

Requirement already satisfied: nltk in c:\users\athen\anaconda3\envs\appliedml\lib\site-packages (3.9.1)
Requirement already satisfied: click in c:\users\athen\anaconda3\envs\appliedml\lib\site-packages (from nltk) (8.3.0)
Requirement already satisfied: joblib in c:\users\athen\anaconda3\envs\appliedml\lib\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\athen\anaconda3\envs\appliedml\lib\site-packages (from nltk) (2025.9.18)
Requirement already satisfied: tqdm in c:\users\athen\anaconda3\envs\appliedml\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\athen\anaconda3\envs\appliedml\lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [10]:
import nltk
nltk.download('vader_lexicon')

from nltk.sentiment import SentimentIntensityAnalyzer

sia = SentimentIntensityAnalyzer()

df["sentiment"] = df["content"].astype(str).apply(lambda x: sia.polarity_scores(x)["compound"])
print(df["sentiment"].head())
print(df["sentiment"].mean())

0    0.3400
1    0.7089
2    0.4754
3    0.7618
4    0.6597
Name: sentiment, dtype: float64
0.27295161290322584

[nltk_data] Error loading vader_lexicon: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>

In [11]:
df["sentiment"].head()

0    0.3400
1    0.7089
2    0.4754
3    0.7618
4    0.6597
Name: sentiment, dtype: float64

In [13]:
df["sentiment"].mean()
df.head()

,title,description,content,publishedAt,source,company,sentiment
0,Searching for new architecture & design jobs? ...,In this week's curated employer highlight from...,In this week's curated employer highlight from...,2025-11-25T15:38:00Z,Archinect,Unknown,0.3400
1,"Alphabet AI chips, Gemini model position it to...","Shares in the Mountain View, California-based ...",A rally in Alphabet shares is poised to shake ...,2025-11-25T15:36:25Z,The Times of India,Alphabet,0.7089
2,Chrome Finally Gets Vertical Tabs After Years ...,Google Chrome is finally catching up to what e...,Google Chrome is finally catching up to what e...,2025-11-25T15:32:34Z,Gadgethacks.com,Alphabet,0.4754
3,Existential OCD: When 'Why Am I Here?' Won’t L...,"What if your endless questions about life, dea...",Picture this: Life looks fine from the outside...,2025-11-25T15:32:05Z,Psychology Today,Unknown,0.7618
4,AMD Stock Tanks Amid Shifting Sands In Semicon...,"Advanced Micro Devices, Inc. (NASDAQ:AMD) shar...","Advanced Micro Devices, Inc. (NASDAQ:AMD) shar...",2025-11-25T15:31:51Z,Biztoc.com,Meta,0.6597

In [7]:
import pandas as pd

df = pd.read_csv("Newdata.csv")
df = df.drop(columns=["sentiment"])
df.head()

,title,description,content,published_at,source,company
0,Alphabet Inc. (GOOGL) shares gain 0.5% on earn...,Alphabet Inc. (GOOGL) shares gain 0.5% on earn...,Alphabet Inc.'s return on invested capital of ...,1/1/2024,WSJ,Alphabet Inc.
1,Meta Platforms Inc. Threads progresses in mark...,Meta Platforms Inc. Threads progresses in mark...,Meta Platforms Inc. (META) demonstrated strate...,1/1/2024,Reuters,Meta Platforms Inc.
2,Meta Platforms Inc. Quest VR faces challenges ...,Meta Platforms Inc. Quest VR faces challenges ...,Manufacturing capacity expansion at Meta Platf...,1/1/2024,WSJ,Meta Platforms Inc.
3,Analysts maintain AAPL following Apple Inc. co...,Analysts maintain AAPL following Apple Inc. co...,Apple Inc. surprised markets with higher reven...,1/1/2024,Reuters,Apple Inc.
4,Tesla Inc. (TSLA) shares gain 3.9% on product ...,Tesla Inc. (TSLA) shares gain 3.9% on product ...,Buy-side analysts point to Tesla Inc.'s produc...,1/1/2024,MarketWatch,Tesla Inc.

In [8]:
import nltk
nltk.download('vader_lexicon')

from nltk.sentiment import SentimentIntensityAnalyzer

sia = SentimentIntensityAnalyzer()

df["sentiment"] = df["content"].astype(str).apply(lambda x: sia.polarity_scores(x)["compound"])
print(df["sentiment"].head())
print(df["sentiment"].mean())

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\athen\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

0    0.7269
1    0.8271
2    0.3612
3    0.2263
4    0.0000
Name: sentiment, dtype: float64
0.5069369122952984

In [11]:

# mask = (df["sentiment"] - df["sentiment_score"]).abs() > 0.5
# df2=df.loc[mask, ["content", "sentiment", "sentiment_score"]]

In [9]:
df.to_csv('a_newdata.csv', index=False)

df.to_json('a_newdata.json', orient='records', force_ascii=False, indent=4)

In [10]:
df = pd.read_csv("a_newdata.csv")
df = df.drop(columns=["sentiment"])
df.to_csv('a_newdata_before_sentiment.csv', index=False)